<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Мебельная компания");?>
<div class="mainpage">
	<div class="container">
	<div class="title"><h2>Кардиганы</h2></div>
		<div class="catalogblock">
			<?$APPLICATION->IncludeComponent(
				"bitrix:catalog", 
				"custom_catalog", 
				array(
					"COMPONENT_TEMPLATE" => "custom_catalog",
					"IBLOCK_TYPE" => "catalog",
					"IBLOCK_ID" => "5",
					"USER_CONSENT" => "N",
					"USER_CONSENT_ID" => "0",
					"USER_CONSENT_IS_CHECKED" => "Y",
					"USER_CONSENT_IS_LOADED" => "N",
					"SEF_MODE" => "N",
					"AJAX_MODE" => "N",
					"AJAX_OPTION_JUMP" => "N",
					"AJAX_OPTION_STYLE" => "Y",
					"AJAX_OPTION_HISTORY" => "N",
					"AJAX_OPTION_ADDITIONAL" => "",
					"CACHE_TYPE" => "A",
					"CACHE_TIME" => "36000000",
					"CACHE_FILTER" => "N",
					"CACHE_GROUPS" => "Y",
					"USE_MAIN_ELEMENT_SECTION" => "N",
					"DETAIL_STRICT_SECTION_CHECK" => "N",
					"SET_LAST_MODIFIED" => "N",
					"SET_TITLE" => "Y",
					"ADD_SECTIONS_CHAIN" => "Y",
					"ADD_ELEMENT_CHAIN" => "N",
					"SECTION_SHOW_PARENT_NAME" => "N",
					"USE_FILTER" => "Y",
					"ACTION_VARIABLE" => "action",
					"PRODUCT_ID_VARIABLE" => "id",
					"USE_COMPARE" => "N",
					"PRICE_CODE" => array(
					),
					"USE_PRICE_COUNT" => "N",
					"SHOW_PRICE_COUNT" => "1",
					"PRICE_VAT_INCLUDE" => "Y",
					"PRICE_VAT_SHOW_VALUE" => "N",
					"BASKET_URL" => "/personal/basket.php",
					"USE_PRODUCT_QUANTITY" => "N",
					"PRODUCT_QUANTITY_VARIABLE" => "quantity",
					"ADD_PROPERTIES_TO_BASKET" => "Y",
					"PRODUCT_PROPS_VARIABLE" => "prop",
					"PARTIAL_PRODUCT_PROPERTIES" => "N",
					"SHOW_TOP_ELEMENTS" => "Y",
					"TOP_ELEMENT_COUNT" => "9",
					"TOP_LINE_ELEMENT_COUNT" => "3",
					"TOP_ELEMENT_SORT_FIELD" => "sort",
					"TOP_ELEMENT_SORT_ORDER" => "asc",
					"TOP_ELEMENT_SORT_FIELD2" => "id",
					"TOP_ELEMENT_SORT_ORDER2" => "desc",
					"SECTION_COUNT_ELEMENTS" => "Y",
					"SECTION_TOP_DEPTH" => "2",
					"PAGE_ELEMENT_COUNT" => "30",
					"LINE_ELEMENT_COUNT" => "3",
					"ELEMENT_SORT_FIELD" => "sort",
					"ELEMENT_SORT_ORDER" => "asc",
					"ELEMENT_SORT_FIELD2" => "id",
					"ELEMENT_SORT_ORDER2" => "desc",
					"INCLUDE_SUBSECTIONS" => "Y",
					"LIST_META_KEYWORDS" => "-",
					"LIST_META_DESCRIPTION" => "-",
					"LIST_BROWSER_TITLE" => "-",
					"SECTION_BACKGROUND_IMAGE" => "-",
					"DETAIL_META_KEYWORDS" => "-",
					"DETAIL_META_DESCRIPTION" => "-",
					"DETAIL_BROWSER_TITLE" => "-",
					"DETAIL_SET_CANONICAL_URL" => "N",
					"SECTION_ID_VARIABLE" => "SECTION_ID",
					"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
					"DETAIL_BACKGROUND_IMAGE" => "-",
					"SHOW_DEACTIVATED" => "N",
					"SHOW_SKU_DESCRIPTION" => "N",
					"DETAIL_SHOW_PICTURE" => "Y",
					"LINK_IBLOCK_TYPE" => "",
					"LINK_IBLOCK_ID" => "",
					"LINK_PROPERTY_SID" => "",
					"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
					"USE_STORE" => "N",
					"PAGER_TEMPLATE" => ".default",
					"DISPLAY_TOP_PAGER" => "N",
					"DISPLAY_BOTTOM_PAGER" => "Y",
					"PAGER_TITLE" => "Товары",
					"PAGER_SHOW_ALWAYS" => "N",
					"PAGER_DESC_NUMBERING" => "N",
					"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
					"PAGER_SHOW_ALL" => "N",
					"PAGER_BASE_LINK_ENABLE" => "N",
					"SET_STATUS_404" => "N",
					"SHOW_404" => "N",
					"MESSAGE_404" => "",
					"COMPATIBLE_MODE" => "N",
					"USE_ELEMENT_COUNTER" => "Y",
					"DISABLE_INIT_JS_IN_COMPONENT" => "N",
					"FILTER_NAME" => "arrFilter",
					"VARIABLE_ALIASES" => array(
						"ELEMENT_ID" => "ELEMENT_ID",
						"SECTION_ID" => "SECTION_ID",
					)
				),
				false
			);?>
		</div>
	</div>
</div>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>